def print_checkbox(self):
  print '\033[0;32m'
  print '  ............................ '
  print ' ..                          ..'
  print ' .                     ..     .'
  print ' .                    .....   .'
  print ' .                   ......   .'
  print ' .                 ......     .'
  print ' .                ......      .'
  print ' .      .        .....        .'
  print ' .    .....    ......         .'
  print ' .     ...... ......          .'
  print ' .      ..........            .'
  print ' .        .......             .'
  print ' .           ...              .'
  print ' ..                          ..'
  print '  ............................ '
